id: 08de0809829c4d679814209058eaa995
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_225-Taking_Refuge_in_the_Three_Jewels-v2
  language: bo
  author: ''
  volume: {}
